### ISSUE TITLE
Performance Improvement: Application List

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/conforma-server#1077]
# Summary

The `application_list` is called a number of times within the application, and can result in slow loading times.

1. It's used to show how many applications are in each category and create a prefiltered view of actionable items for users
![image](https://github.com/msupply-foundation/conforma-server/assets/8287373/3d6c45ac-750c-4cd7-9984-9ecc2706f644)
> A lot of these could run concurrently but the number of concurrent requests is limited to 5 by chrome.

2. It's used when displaying a filtered list of actionable items for a user

![image](https://github.com/msupply-foundation/conforma-server/assets/8287373/67cbfe5f-ee0c-4597-bd57-465e1acdf76b)
![image](https://github.com/msupply-foundation/conforma-server/assets/8287373/0d21b5a5-c6dd-4cb4-aaf5-cf9594433d85)

# Why is it slow?

Because `application_list` is implemented as a function, and the postgraphile filters are applied to the result of the function, the entire function has to run even to return a count(*) - Postgres sees the function as a black box. Without the function overhead it looks like the query could run a lot faster.

SELECT count(*) FROM (SELECT ....) as application_list

![Pasted image 20231117094258](https://github.com/msupply-foundation/conforma-server/assets/8287373/1cf292e8-71a8-420e-98b3-c541a5033815)

 SELECT count(*) FROM application_list('2')
![image](https://github.com/msupply-foundation/conforma-server/assets/8287373/d907d5f3-66a5-4e8f-9a72-c732444f212c)

# How concerned are we?

Performance seems to be linearly related to the number of applications in the system, the more applications in the system the slower it could become. So it's important that we resolve this!

# Possible Solutions:

- [ ] Run query as a parameterised query outside of PostGraphile
- [ ] Change filters to be function parameters rather than postgraphile filters?
- [ ] Dedicated Count function (maybe?)
- [ ] Store application list data per user, and recalculate automatically, either was some kind of materialised view or code that runs? - This seems like it could be complex?
- [ ] Some kind of global filter/where clause parameter that can exclude the majority of applications once they're completed?
- [ ] Something else? 

# Agreed Solution
TBD

**Comment by andreievg** [comment]
> Postgres sees the function as a black box. Without the function overhead it looks like the query could run a lot faster.

I've tested with and without function overhead, there was no difference. Create bench.sql with "select * from application_list(54)", make sure user 54 exists, and run `pgbench -f bench.sql --log --transactions=30 --username=postgres tmf_app_manager` and similar with content of application list, but replacing userId with 54. (although I didn't test with SELECT count(*) FROM (SELECT ....) as application_list, I don't think the issue is with 

## The biggest problem in my test were:
1 - Calling applicationList three times in applicationList view (as pointed out by @jmbrunskill), this is because query is getting pageInfo and total count for pagination.
2 - Row level policies, mainly because it's using manual "in" clause and extracted array from JWT token (postgres doesn't optimise these queries), queries without row policies run up to 4 times quicker.
3 - review_assignment_available_sections method used in in one of the WHERE clauses look like it will run for every row 

Other things I tried (using the bench method above, and just modifying the select statement in bench.sql):
* Instead of count(*) use bool_or, i.e. `CASE WHEN COUNT(*) FILTER (WHERE action_review_status_history.status = 'CHANGES_REQUESTED') != 0 THEN 'UPDATE_REVIEW'` -> `CASE WHEN BOOL_OR(action_review_status_history.status = 'CHANGES_REQUESTED') THEN 'UPDATE_REVIEW'`, seems to make no difference
* Indexing status on review_status_history, small increase in performance, a few percent.

Most tests were done with anonymised data file given by @CarlosNZ with Emi user.

## Improvements

Problem 1 -> Quite easily done on front end, get count after getting application list. It looks like pageInfo is not even used, should lead to 3 x speed improvement

Problem 2 -> I've tried using in statement as a select statement, from 900ms to around 350ms, which I think is worth pursuing (and it should scale a lot better)

Problem 3 -> This can be done as a view/function and joined, this looks like it's making the query around 1.5 faster.

With those 3 fixed, I got down to around 320ms for application list query (on my mac), and that's with row level permissions

## Further investigation and improvements

Might be able to optimise assigner actions a bit, by not pre-grouping in a view, but doing the grouping in the application_list method

Need to add tests for all variations of actions in application list

Diagram and full explanation of application_list function/query.
